### ISSUE TITLE
Node 14.15.3 is breaking modules install

### ISSUE THREAD

**Issue by ipanasenko** [wix/wix-ui#1988]
Node 14.15.3 came out and I can't install modules with it. This is an error I see:

```
error /Users/ilyap/Projects/add-panel/node_modules/wix-ui-core: Command failed.
Exit code: 1
Command: npm install @stylable/dom-test-kit --no-save
Arguments:
Directory: /Users/ilyap/Projects/add-panel/node_modules/wix-ui-core
Output:
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '../lib/utils/unsupported.js'
Require stack:
- /Users/ilyap/.nvm/versions/node/v14.15.3/lib/node_modules/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /Users/ilyap/.nvm/versions/node/v14.15.3/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/Users/ilyap/.nvm/versions/node/v14.15.3/lib/node_modules/npm/bin/npm-cli.js:155:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
```

Node 14.15.2 works fine. Don't know if it's Node bug or wix-ui-core or stylable

**Comment by shlomitc** [comment]
I npm installed `wix-ui-core` with node@14 and it seems ok.
Do you have more details?
@barak007 cc

**Comment by barak007** [comment]
Worked fine for me. 
Node: v14.15.3

```
+ wix-ui-core@3.0.165
added 178 packages from 497 contributors and audited 178 packages in 129.173s

26 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

```

**Comment by ipanasenko** [comment]
Sorry I didn't mention I used `yarn`. Also, if this helps, repo is https://github.com/wix-private/add-panel. Right not we have 14.15.2 everywhere in .nvmrc, but you can check on this commit, before the .nvmrc fix: 37fff64bfdf08c95b9c9f5fe7b8b49712c76534f

**Comment by shlomitc** [comment]
Works on my machine also in the above commit with 14.15.3
Maybe it was a broken node/npm version?

**Comment by ipanasenko** [comment]
Maybe, I don't know. Anyway, 14.15.2 works fine for me, so no big deal. Thanks!
