### ISSUE TITLE
Can not create auto-story - FieldWithSelection (WSR)

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#319]
I am getting this error when adding a story for the FieldWithSelectionTemplate (The FieldWithSelectionComposite's example):
I want to have a story of the example, for testing.
```
ERROR in ./stories/FieldWithSelectionComposite/FieldWithSelectionTest.story.js
Module build failed: TypeError: Cannot read property 'find' of null
    at propertyName (/Users/erezm/Projects/wix-style-react/node_modules/react-autodocs-utils/src/path-finder/index.js:9:5)
    at ExportDefaultDeclaration (/Users/erezm/Projects/wix-style-react/node_modules/react-autodocs-utils/src/path-finder/index.js:17:57)
    at NodePath._call (/Users/erezm/Projects/wix-style-react/node_modules/@babel/traverse/lib/path/context.js:64:19)
    at NodePath.call (/Users/erezm/Projects/wix-style-react/node_modules/@babel/traverse/lib/path/context.js:38:17)
    at NodePath.visit (/Users/erezm/Projects/wix-style-react/node_modules/@babel/traverse/lib/path/context.js:99:12)
    at TraversalContext.visitQueue (/Users/erezm/Projects/wix-style-react/node_modules/@babel/traverse/lib/context.js:135:18)
    at TraversalContext.visitMultiple (/Users/erezm/Projects/wix-style-react/node_modules/@babel/traverse/lib/context.js:89:17)
    at TraversalContext.visit (/Users/erezm/Projects/wix-style-react/node_modules/@babel/traverse/lib/context.js:174:19)
    at Function.traverse.node (/Users/erezm/Projects/wix-style-react/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/Users/erezm/Projects/wix-style-react/node_modules/@babel/traverse/lib/path/context.js:106:18)
    at TraversalContext.visitQueue (/Users/erezm/Projects/wix-style-react/node_modules/@babel/traverse/lib/context.js:135:18)
    at TraversalContext.visitSingle (/Users/erezm/Projects/wix-style-react/node_modules/@babel/traverse/lib/context.js:94:19)
    at TraversalContext.visit (/Users/erezm/Projects/wix-style-react/node_modules/@babel/traverse/lib/context.js:176:19)
    at Function.traverse.node (/Users/erezm/Projects/wix-style-react/node_modules/@babel/traverse/lib/index.js:76:17)
    at traverse (/Users/erezm/Projects/wix-style-react/node_modules/@babel/traverse/lib/index.js:46:12)
    at visitor (/Users/erezm/Projects/wix-style-react/node_modules/react-autodocs-utils/src/parser/visit.js:4:3)
 @ ./.storybook/stories.js 39:0-81
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js (webpack)-hot-middleware/client.js?reload=true ./.storybook/config.js
```

See this branch:
https://github.com/wix/wix-style-react/tree/focus/14a-field-with-selection-story

**Comment by argshook** [comment]
`react-autodocs-utils` didn't consider referenced config object and only worked with `export default {}`. I fixed this, you should get this working once `wix-storybook-utils` is released

**Comment by argshook** [comment]
this is fixed and release, please reopen if im wrong
