### ISSUE TITLE
Cannot create story for Input

### ISSUE THREAD

**Issue by alisey** [wix/wix-ui#334]
I took existing Input story and tried to make it look more like other stories, i.e. to use createStory() function:

```
import * as React from 'react';
import {Input} from '../../src/components/Input';
import createStory from '../create-story';
import * as InputSource from '!raw-loader!../../src/components/Input/Input.tsx';

export const story = () => createStory({
  category: 'Components',
  storyName: 'Input',
  name: 'Input',
  component: Input,
  source: InputSource,

  componentProps: setState => ({
    'data-hook': 'storybook-input',
    value: '',
    onChange: ({target: {value}}) => setState({value}),
  }),

  exampleProps: {
    onClick: () => 'Triggered onClick',
    onChange: () => 'Triggered onChange',
    onDoubleClick: () => 'Triggered onDoubleClick',
    onBlur: () => 'Triggered onBlur',
    onFocus: () => 'Triggered onFocus',
    onKeyDown: () => 'Triggered onKeyDown',
    onKeyUp: () => 'Triggered onKeyUp'
  }
});
```

When trying to load this in browser I'm getting a cryptic error:
```
Unexpected token (85:10)
SyntaxError: Unexpected token (85:10)
    at Parser.pp.raise (http://localhost:6006/static/preview.bundle.js:152416:13)
    at Parser.pp.unexpected (http://localhost:6006/static/preview.bundle.js:150351:8)
    at Parser.pp.expect (http://localhost:6006/static/preview.bundle.js:150345:33)
    at Parser.pp.parseMethod (http://localhost:6006/static/preview.bundle.js:152155:8)
    at Parser.parseClassMethod (http://localhost:6006/static/preview.bundle.js:153433:27)
    at Parser.pp.parseClass (http://localhost:6006/static/preview.bundle.js:150954:10)
    at Parser.pp.parseStatement (http://localhost:6006/static/preview.bundle.js:150442:19)
    at Parser.parseStatement (http://localhost:6006/static/preview.bundle.js:153236:22)
    at Parser.pp.parseExportDeclaration (http://localhost:6006/static/preview.bundle.js:151067:15)
    at Parser.parseExportDeclaration (http://localhost:6006/static/preview.bundle.js:153325:22)
```

HALP.

**Comment by argshook** [comment]
@alisey im working on this exact story also. however, im working on it without using `createStory` and instead using magic webpack loader. this essentially is the future for all stories: generate them build time and not runtime with `createStory`

i suppose you can leave it for the time being. or if you are really interested, catch me on slack :)

**Comment by alisey** [comment]
Great, will leave it to you then.
