### ISSUE TITLE
wix-storybook-utils: Unable to handle composed props

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#438]
Getting this when building storybook of `wix-ui-core`:
```
info Building storybook ...
(node:52866) DeprecationWarning: importing default webpack config generator from '@storybook/react/dist/server/config/defaults/webpack.config.js' is deprecated. Use third argument of your exported function instead. See https://storybook.js.org/configurations/custom-webpack-config/#full-control-mode--default
ERROR: Unable to handle composed props TypeError: Cannot read property 'map' of undefined
    at handleComposedProps (/Users/erezm/Projects/wix-ui/packages/wix-ui-core/node_modules/react-autodocs-utils/src/follow-props/index.js:33:21)
    at parseDocgen.catch.parsed (/Users/erezm/Projects/wix-ui/packages/wix-ui-core/node_modules/react-autodocs-utils/src/follow-props/index.js:101:7)
    at <anonymous>
ERROR: Unable to handle composed props TypeError: Cannot read property 'map' of undefined
    at handleComposedProps (/Users/erezm/Projects/wix-ui/packages/wix-ui-core/node_modules/react-autodocs-utils/src/follow-props/index.js:33:21)
    at parseDocgen.catch.parsed (/Users/erezm/Projects/wix-ui/packages/wix-ui-core/node_modules/react-autodocs-utils/src/follow-props/index.js:101:7)
    at <anonymous>
info Building storybook completed.
```

**Comment by argshook** [comment]
@hepiyellow error out of blue from existing stories or some new component story?

**Comment by argshook** [comment]
@hepiyellow still remember where you saw this? i can't solve properly without knowing what to look at :)

**Comment by argshook** [comment]
closing, please reopen if it still happens
