### ISSUE TITLE
wix-storybook-utils - Error when propTypes has an undefined spread

### ISSUE THREAD

**Issue by hepiyellow** [wix/wix-ui#858]
I saw this error when storybook is loading a page of a component:
```
  TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at ../node_modules/wix-storybook-utils/dist/src/AutoExample/utils/omit.js.exports.default (http://localhost:6006/static/preview.bundle.js:272181:19)
    at StoryPage (http://localhost:6006/static/preview.bundle.js:272802:120)
    at p._constructComponentWithoutOwner (https://static.parastorage.com/unpkg/react-dom@15.6.0/dist/react-dom.min.js:13:6267)
    at p._constructComponent (https://static.parastorage.com/unpkg/react-dom@15.6.0/dist/react-dom.min.js:13:6121)
    at p.mountComponent (https://static.parastorage.com/unpkg/react-dom@15.6.0/dist/react-dom.min.js:13:5303)
    at Object.mountComponent (https://static.parastorage.com/unpkg/react-dom@15.6.0/dist/react-dom.min.js:14:18996)
    at performInitialMount (https://static.parastorage.com/unpkg/react-dom@15.6.0/dist/react-dom.min.js:13:7073)
    at p.mountComponent (https://static.parastorage.com/unpkg/react-dom@15.6.0/dist/react-dom.min.js:13:5962)
    at Object.mountComponent (https://static.parastorage.com/unpkg/react-dom@15.6.0/dist/react-dom.min.js:14:18996)
        ```

My component has this :
```
Avatar.propTypes = {
  ...CoreAvatar.propTypes
};
```

while CoreAvatar.propTypes is `undefined`.
This is of course not what I meant, and I should not spread an undefined variable onto `CoreAvatar.proptypes`.

But still, wix-storybook-utils shouldn't break on that (javascript doesn't break).
Or at least it should give a more informative error.

**Comment by argshook** [comment]
no longer relevant
